### ISSUE TITLE
Grid modelling

### ISSUE THREAD

**Issue by Varat7v2** [tahanakabi/DRL-for-microgrid-energy-management#4]
Hi @tahanakabi, Thank you for sharing the project. I have a confusion on grid modelling #line 181: why are you dividing (prices*energy) by 100?

For your reference, I have put the link of the code line here.  

https://github.com/tahanakabi/DRL-for-microgrid-energy-management/blob/17b20c3df0ab827b319b86966af5ab1268d8e61e/tcl_env_dqn_1.py#L181C8-L181C67

Thank you for your time.

**Comment by shami2017** [comment]
@Varat7v2 
I think for cent to euro conversion.

**Comment by tahanakabi** [comment]
@shami2017 Correct
