### ISSUE TITLE
Battery charge model

### ISSUE THREAD

**Issue by shami2017** [tahanakabi/DRL-for-microgrid-energy-management#5]
Hi Taha,

Excellent work done by you - Thanks

I think this leftover is not working properly in a few cases of charge/discharge.

I am sharing the link to the reference line:
https://github.com/tahanakabi/DRL-for-microgrid-energy-management/blob/17b20c3df0ab827b319b86966af5ab1268d8e61e/tcl_env_dqn_1.py#L138C13-L138C70

It requires some modification.

Thanks

**Comment by tahanakabi** [comment]
Hi @shami2017 thanks for your feedback. There was indeed a mistake there. It was modified in commit 579ee1f24e3233095c0cf87934fbe5937d402d50
